# NightCode Game Ideas Library (Auto-updated by LLM Q)
FAMOUS_IDEAS = [
    "A classic Snake game where the snake grows longer as it eats apples.",
    "A Pong clone with a neon aesthetic and AI opponent.",
    "A Breakout/Arkanoid game where the player bounces a ball to break bricks.",
    "An Asteroids clone where the player shoots flying space rocks.",
    "A Tetris-style block stacking puzzle game.",
    "A Space Invaders style shooter with descending alien waves.",
    "A simple Flappy Bird clone where you click to fly through pipes.",
    "A top-down 2D maze game where you collect coins and avoid ghosts (Pac-Man style).",
    "A Frogger clone where the player crosses a busy road and a river.",
    "A Galaga-style space shooter where enemies dive bomb the player.",
    "A 2048 number sliding puzzle game.",
    "A classic Minesweeper game with a grid and flags.",
    "A Sudoku puzzle game with a 9x9 grid.",
    "A Tic-Tac-Toe game with a smart AI opponent using the minimax algorithm.",
    "A Connect Four game with falling discs and win detection.",
    "A Memory Match card game where you flip cards to find pairs.",
    "A Simon Says rhythm memory game with colored buttons.",
    "A Whack-a-Mole game where moles pop up from holes and you click them.",
    "A Doodle Jump clone where you jump up infinitely on platforms.",
    "A Geometry Dash style rhythm platformer with a square that jumps over spikes.",
    "A Helicopter game where you hold the mouse to fly up and release to drop.",
    "A Qix-style game where you draw lines to claim territory while avoiding enemies.",
    "A Centipede clone where you shoot a segmented centipede winding down the screen.",
    "A Mini Golf game with physics and obstacles.",
    "A Bubble Shooter game where you match 3 colors to pop bubbles.",
    "A Zuma clone where you shoot colored balls into a moving chain.",
    "A Tower Stacking game where you drop blocks to build the tallest tower.",
    "A Sokoban box-pushing puzzle game.",
    "A Lunar Lander game where you safely land a ship on a pad using thrusters.",
    "A Missile Command game where you shoot down incoming rockets.",
    "A Chrome Dinosaur Runner game where you jump over cacti and duck under birds.",
    "A Slither.io clone where you eat pellets to grow and avoid other snakes.",
    "An Agar.io style game where you eat smaller circles to grow.",
    "A 2-player Tank game where tanks shoot projectiles at each other.",
    "A Top-Down 2D Racing game with a lap counter.",
    "A Vertical Scrolling Shooter (like 1942) with power-ups.",
    "A Horizontal Scrolling Shooter (like Gradius).",
    "A simple Pinball game with flippers and bumpers.",
    "An Air Hockey game with mallets and a puck.",
    "A Brick Breaker game with power-ups like multi-ball and lasers.",
    "A Sokoban puzzle with multiple boxes and targets.",
    "A Top-Down Zombie Survival shooter with waves of zombies.",
    "A Maze Runner game where you find the exit in a randomly generated maze.",
    "A Pong clone with a twist: the ball leaves a glowing trail and speeds up.",
    "A Flappy Bird clone with a spaceship theme and asteroids to dodge.",
    "A Snake game with portals that teleport you across the screen.",
    "A Tetris clone with neon blocks and a ghost piece preview.",
    "A Breakout clone where the paddle moves in a circle around the screen.",
    "A Space Invaders clone with destructible bunkers.",
    "A 2D platformer where you collect coins and reach the exit door.",
    "An Angry Birds clone where you slingshot birds at structures to knock them down.",
    "A World of Goo style physics puzzle where you build bridges out of goo balls.",
    "A Donkey Kong style arcade game where you climb ladders and jump over barrels.",
    "A BurgerTime clone where you build burgers by walking over ingredients.",
    "A Dig Dug clone where you dig tunnels and inflate enemies until they pop.",
    "A Mr. Do! style game where you dig and throw a power ball at enemies.",
    "A Berzerk clone where you navigate a maze and shoot robots while avoiding walls.",
    "A Tempest clone where you move around the edge of a 3D-looking web and shoot enemies.",
    "A Gyruss clone where you rotate in a circle and shoot ships flying toward the center.",
    "A Moon Patrol clone where you drive a moon buggy shooting aliens and jumping craters.",
    "A Scramble clone where you fly a ship horizontally, shooting enemies and dropping bombs.",
    "A Defender clone where you protect humans from aliens in a wrapping 2D world.",
    "A Robotron clone where you move with one stick and shoot in 8 directions with another.",
    "A Joust clone where you ride flying ostriches and joust enemies.",
    "A Dr. Mario clone where you drop colored pills to destroy matching viruses.",
    "A Columns clone where you match falling colored gems horizontally, vertically, or diagonally.",
    "A Picross puzzle game where you color a grid based on number clues to reveal an image.",
    "A Pipe Mania clone where you place pipe pieces to route water before it overflows.",
    "A Peg Solitaire game where you jump pegs to remove them, aiming for one left.",
    "A classic 15-puzzle sliding tile game to arrange numbers in order.",
    "A Bejeweled clone where you swap adjacent gems to match 3 or more.",
    "A Lumines style puzzle where you drop 2x2 blocks and clear them with a sweeping line.",
    "A Lemmings style game where you assign skills to walking creatures to reach the exit.",
    "A Cannon shooter game where you adjust angle and power to hit moving targets.",
    "An Archery game where you account for wind and gravity to hit a bullseye.",
    "A Bowling game with realistic pin physics and spin controls.",
    "A Basketball shootout game where you drag and release to shoot hoops.",
    "A Penalty Kick game where you aim and kick a soccer ball past a diving goalie.",
    "A Home Run Derby game where you time your swing to hit incoming baseballs.",
    "A Volleyball game where two players jump and hit a ball over a net.",
    "A Table Tennis (Ping Pong) game with fast-paced paddle hits.",
    "A Tower Defense game where you place turrets to stop waves of enemies.",
    "A Checkers game with jumping and king mechanics against an AI.",
    "A Battleship game where you place ships and guess enemy coordinates.",
    "An Othello (Reversi) game where you flip opponent discs by sandwiching them.",
    "A Tamagotchi virtual pet game where you feed, clean, and play with a creature.",
    "An Idle Clicker game where you buy upgrades to generate resources automatically.",
    "A Paperboy clone where you ride a bike and throw newspapers at houses.",
    "A Tapper clone where you serve drinks to customers before they reach the end of the bar.",
    "A Diner Dash style game where you seat and serve customers efficiently.",
    "A Vampire Survivors style game where you automatically attack and survive hordes.",
    "A Piano Tiles game where you click black tiles as they fall to play a song.",
    "A StepMania clone where you hit arrow keys to the rhythm of the music.",
    "A physics-based crate stacking game where you balance crates on a swaying ship.",
    "A Bridge Builder puzzle where you construct a bridge within a budget to let vehicles cross.",
    "An endless racing game where you dodge traffic at high speeds.",
    "A Trials-style motorcycle game where you balance and jump over obstacles.",
    "A slalom skiing game where you weave between flags on a downhill slope.",
    "A Diep.io clone where you shoot shapes to level up and upgrade your tank.",
    "A Surviv.io style top-down battle royale where you loot and survive in a shrinking zone.",
    "A simple Go game where you surround territory on a grid.",
    "A Chess game with standard rules and piece movements.",
    "A hack-and-slash arena game where you fight waves of melee enemies.",
    "A stealth game where you avoid vision cones to reach an exit.",
    "A cooking game where you assemble ingredients to match orders under time pressure.",
    "A Plague Inc style game where you evolve a virus to infect the world.",
    "A city builder game where you zone residential, commercial, and industrial areas.",
    "A farming simulator where you plant, water, and harvest crops to sell.",
    "A Ragdoll Volleyball game where physics-based characters try to hit a ball.",
    "A basketball physics game where you drop a ball into a hoop using drawn lines.",
    "A BoxWorld puzzle where you push boxes onto targets.",
    "A Hashi (Bridges) puzzle where you connect islands with bridges.",
    "A Nonogram puzzle game where you fill a grid based on row and column numbers.",
    "An N+ style ninja platformer where you wall-jump and collect gold.",
    "A Bit.Trip Runner style auto-runner where you jump, slide, and kick to the beat.",
    "A Super Meat Boy style hardcore platformer with precise controls and hazards.",
    "A VVVVVV style gravity-flipping platformer where you navigate a maze.An Among Us based game with multiple maps and multiple roles.",
    "A Snake game where the snake leaves a trail of fire.",
    "A Pong clone with 3 balls.",
    "A platformer where gravity flips every 5 seconds.",
    "A top-down shooter where bullets ricochet off walls.",
    "A puzzle game where you control two characters simultaneously.",
    "A racing game where the track is drawn by the player.",
    "A rhythm game where you dodge obstacles to the beat.",
    "A tower defense game where towers are living creatures.",
    "A space shooter where you absorb enemy ships to grow.",
    "A stealth game where you are a ghost haunting a house.",
    "A match-3 game with physics-based falling blocks.",
    "A clicker game where you evolve a cell into a complex organism.",
    "A memory game where the tiles move after every turn.",
    "A runner game where the world rotates 90 degrees.",
    "A combat game where you fight using only a grappling hook.",
    "A puzzle game where you manipulate time to solve riddles.",
    "A fishing game where you catch cosmic entities.",
    "A golf game where the ball can teleport.",
    "A maze game where the walls shift based on your movement.",
    "A shooter where your health is your ammo.",
    "A platformer where you can only jump when touching a specific color.",
    "A strategy game where you command an army of ants.",
    "A puzzle game where you connect pipes to guide light.",
    "A racing game where you drive on the ceiling.",
    "A combat game where you fight by drawing shapes.",
    "A stealth game where you blend into the background colors.",
    "A space game where you build a station from debris.",
    "A runner game where you switch between 2D and 3D.",
    "A puzzle game where you rotate the entire level.",
    "A shooter where bullets slow down time.",
    "A platformer where you grow larger by eating.",
    "A memory game where you recreate a pattern of sounds.",
    "A racing game where the car shrinks over time.",
    "A combat game where you fight with a magnetic pole.",
    "A puzzle game where you mirror your movements.",
    "A stealth game where you are a spy in a museum.",
    "A space game where you herd asteroids.",
    "A runner game where you jump between parallel dimensions.",
    "A puzzle game where you slide blocks to form a circuit.",
    "A shooter where you shoot portals to redirect fire.",
    "A platformer where you can freeze water into ice.",
    "A memory game where you remember a sequence of colors.",
    "A racing game where you leave a trail of ice.",
    "A combat game where you fight using sound waves.",
    "A puzzle game where you balance a scale with objects.",
    "A stealth game where you hide in shadows.",
    "A space game where you navigate a black hole.",
    "A runner game where you change size to fit gaps.",
    "A puzzle game where you fold the screen like paper.",
    "A shooter where you shoot seeds that grow into walls.",
    "A platformer where you control a bubble.",
    "A memory game where you match scents.",
    "A racing game where you drive a shopping cart.",
    "A combat game where you fight with a yo-yo.",
    "A puzzle game where you guide a marble through a maze.",
    "A stealth game where you are a cat stealing fish.",
    "A space game where you mine crystals from planets.",
    "A runner game where you run on a giant record player.",
    "A puzzle game where you swap positions with enemies.",
    "A shooter where you shoot ink to blind foes.",
    "A platformer where you can climb any surface.",
    "A memory game where you recall a map.",
    "A racing game where the road is made of conveyor belts.",
    "A combat game where you fight with a giant fan.",
    "A puzzle game where you use magnets to move keys.",
    "A stealth game where you are a ninja in a library.",
    "A space game where you launch satellites to map a galaxy.",
    "A runner game where you run on a tightrope.",
    "A puzzle game where you connect stars to form constellations.",
    "A shooter where you shoot bubbles to trap enemies.",
    "A platformer where you can change the weight of objects.",
    "A memory game where you match symbols in a grid.",
    "A racing game where you drive a soapbox car.",
    "A combat game where you fight with a boomerang.",
    "A puzzle game where you use mirrors to reflect lasers.",
    "A stealth game where you are a mouse in a kitchen.",
    "A space game where you dodge solar flares.",
    "A runner game where you run on a floating ribbon.",
    "A puzzle game where you arrange gears to turn a wheel.",
    "A shooter where you shoot paint to reveal hidden paths.",
    "A platformer where you can dash through walls.",
    "A memory game where you remember a sequence of notes.",
    "A racing game where you drive a hovercraft on water.",
    "A combat game where you fight with a whip.",
    "A puzzle game where you use wind to push objects.",
    "A stealth game where you are a chameleon.",
    "A space game where you orbit planets to gain speed.",
    "A runner game where you run on a giant keyboard.",
    "A puzzle game where you fit Tetris pieces into a circle.",
    "A shooter where you shoot electricity that chains.",
    "A platformer where you can switch between fire and water forms.",
    "A memory game where you match silhouettes.",
    "A racing game where you drive a snail.",
    "A combat game where you fight with a shield only.",
    "A puzzle game where you use a lens to zoom in on clues.",
    "A stealth game where you are a shadow.",
    "A space game where you build a rocket from scrap.",
    "A runner game where you run on a spiral.",
    "A puzzle game where you balance a stack of plates."
]