# NightCode Game Ideas Library
# 50 classic game concepts optimized for HTML5 Canvas generation

FAMOUS_IDEAS = [
    "A classic Snake game where the snake grows longer as it eats apples.",
    "A Pong clone with a neon aesthetic and AI opponent.",
    "A Breakout/Arkanoid game where the player bounces a ball to break bricks.",
    "An Asteroids clone where the player shoots flying space rocks.",
    "A Tetris-style block stacking puzzle game.",
    "A Space Invaders style shooter with descending alien waves.",
    "A simple Flappy Bird clone where you click to fly through pipes.",
    "A top-down 2D maze game where you collect coins and avoid ghosts (Pac-Man style).",
    "A Frogger clone where the player crosses a busy road and a river.",
    "A Galaga-style space shooter where enemies dive bomb the player.",
    "A 2048 number sliding puzzle game.",
    "A classic Minesweeper game with a grid and flags.",
    "A Sudoku puzzle game with a 9x9 grid.",
    "A Tic-Tac-Toe game with a smart AI opponent using the minimax algorithm.",
    "A Connect Four game with falling discs and win detection.",
    "A Memory Match card game where you flip cards to find pairs.",
    "A Simon Says rhythm memory game with colored buttons.",
    "A Whack-a-Mole game where moles pop up from holes and you click them.",
    "A Doodle Jump clone where you jump up infinitely on platforms.",
    "A Geometry Dash style rhythm platformer with a square that jumps over spikes.",
    "A Helicopter game where you hold the mouse to fly up and release to drop.",
    "A Qix-style game where you draw lines to claim territory while avoiding enemies.",
    "A Centipede clone where you shoot a segmented centipede winding down the screen.",
    "A Mini Golf game with physics and obstacles.",
    "A Bubble Shooter game where you match 3 colors to pop bubbles.",
    "A Zuma clone where you shoot colored balls into a moving chain.",
    "A Tower Stacking game where you drop blocks to build the tallest tower.",
    "A Sokoban box-pushing puzzle game.",
    "A Lunar Lander game where you safely land a ship on a pad using thrusters.",
    "A Missile Command game where you shoot down incoming rockets.",
    "A Chrome Dinosaur Runner game where you jump over cacti and duck under birds.",
    "A Slither.io clone where you eat pellets to grow and avoid other snakes.",
    "An Agar.io style game where you eat smaller circles to grow.",
    "A 2-player Tank game where tanks shoot projectiles at each other.",
    "A Top-Down 2D Racing game with a lap counter.",
    "A Vertical Scrolling Shooter (like 1942) with power-ups.",
    "A Horizontal Scrolling Shooter (like Gradius).",
    "A simple Pinball game with flippers and bumpers.",
    "An Air Hockey game with mallets and a puck.",
    "A Brick Breaker game with power-ups like multi-ball and lasers.",
    "A Sokoban puzzle with multiple boxes and targets.",
    "A Top-Down Zombie Survival shooter with waves of zombies.",
    "A Maze Runner game where you find the exit in a randomly generated maze.",
    "A Pong clone with a twist: the ball leaves a glowing trail and speeds up.",
    "A Flappy Bird clone with a spaceship theme and asteroids to dodge.",
    "A Snake game with portals that teleport you across the screen.",
    "A Tetris clone with neon blocks and a ghost piece preview.",
    "A Breakout clone where the paddle moves in a circle around the screen.",
    "A Space Invaders clone with destructible bunkers.",
    "A 2D platformer where you collect coins and reach the exit door."
]
